export const OPEN_MODAL_ORDER_DETAILS: "OPEN_MODAL_ORDER_DETAILS" = "OPEN_MODAL_ORDER_DETAILS";
export const CLOSE_MODAL_ORDER_DETAILS:"CLOSE_MODAL_ORDER_DETAILS" = "CLOSE_MODAL_ORDER_DETAILS";
export const SUBMIT_ORDER_NUMBER_SUCCESS:"SUBMIT_ORDER_NUMBER_SUCCESS" = "SUBMIT_ORDER_NUMBER_SUCCESS";
export const SUBMIT_ORDER_NUMBER_REQUEST:"SUBMIT_ORDER_NUMBER_REQUEST" = "SUBMIT_ORDER_NUMBER_REQUEST";
export const SUBMIT_ORDER_NUMBER_FAILED:"SUBMIT_ORDER_NUMBER_FAILED" = "SUBMIT_ORDER_NUMBER_FAILED";
export const GET_ORDER_SUCCESS:"GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";