export const GET_INGREDIENTS_REQUEST:"GET_INGREDIENTS_REQUEST" = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_FAILED:"GET_INGREDIENTS_FAILED" = "GET_INGREDIENTS_FAILED";
export const GET_INGREDIENTS_SUCCESS:"GET_INGREDIENTS_SUCCES" = "GET_INGREDIENTS_SUCCES";
export const GET_SELECTED_INGREDIENTS:"GET_SELECTED_INGREDIENTS" = "GET_SELECTED_INGREDIENTS";
export const SWITCH_TAB:"SWITCH_TAB" = "SWITCH_TAB";