export const SET_BUN:"SET_BUN" = "SET_BUN";
export const SET_INGREDIENTS:"SET_INGREDIENTS" = "SET_INGREDIENTS";
export const DELETE_INGREDIENTS:"DELETE_INGREDIENTS" = "DELETE_INGREDIENTS";
export const DRAG_INGREDIENTS:"DRAG_INGREDIENTS" = "DRAG_INGREDIENTS";
export const CLEAN_INGREDIENTS:"CLEAN_INGREDIENTS" = "CLEAN_INGREDIENTS";